apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flights.fullname" . }}-analytics-worker
  labels:
    {{- include "flights.labels" . | nindent 4 }}
    app.kubernetes.io/component: analytics-worker
spec:
  replicas: {{ .Values.analyticsWorker.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/component: analytics-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: analytics-worker
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: worker
          image: "{{ .Values.analyticsWorker.image.repository }}:{{ .Values.analyticsWorker.image.tag }}"
          imagePullPolicy: {{ .Values.analyticsWorker.image.pullPolicy }}
          ports:
            - name: metrics
              containerPort: {{ .Values.analyticsWorker.metricsPort }}
          envFrom:
            - configMapRef:
                name: {{ include "flights.fullname" . }}-analytics-worker
          resources:
            {{- toYaml .Values.analyticsWorker.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: metrics
            initialDelaySeconds: 20
            periodSeconds: 20