{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flights.fullname" . }}-api
  labels:
    {{- include "flights.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.api }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "flights.fullname" . }}-api
                port:
                  number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flights.fullname" . }}-grafana
  labels:
    {{- include "flights.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.grafana }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "flights.fullname" . }}-grafana
                port:
                  number: {{ .Values.grafana.port }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flights.fullname" . }}-jaeger
  labels:
    {{- include "flights.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.jaeger }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "flights.fullname" . }}-jaeger
                port:
                  number: {{ .Values.jaeger.uiPort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flights.fullname" . }}-rabbitmq
  labels:
    {{- include "flights.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.rabbit }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "flights.fullname" . }}-rabbitmq
                port:
                  number: {{ .Values.rabbitmq.managementPort }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "flights.fullname" . }}-prometheus
  labels:
    {{- include "flights.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.prometheus }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "flights.fullname" . }}-prometheus
                port:
                  number: {{ .Values.prometheus.port }}
{{- end -}}