// <auto-generated />
using System;
using System.Collections.Generic;
using FlightCatalog.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FlightCatalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FlightCatalogDbContext))]
    [Migration("20260915165246_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("flight_catalog")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FlightCatalog.Domain.Aggregates.Airport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("city");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("airport_code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("timezone");

                    b.ComplexProperty<Dictionary<string, object>>("Coordinates", "FlightCatalog.Domain.Aggregates.Airport.Coordinates#Coordinates", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("latitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("longitude");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("airports", "flight_catalog");
                });

            modelBuilder.Entity("FlightCatalog.Domain.Aggregates.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AircraftModel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("aircraft_model");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.ComplexProperty<Dictionary<string, object>>("FlightNumber", "FlightCatalog.Domain.Aggregates.Flight.FlightNumber#FlightNumber", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("character varying(10)")
                                .HasColumnName("flight_no");
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Route", "FlightCatalog.Domain.Aggregates.Flight.Route#Route", b1 =>
                        {
                            b1.IsRequired();

                            b1.ComplexProperty<Dictionary<string, object>>("Arrival", "FlightCatalog.Domain.Aggregates.Flight.Route#Route.Arrival#AirportCode", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("arrival_airport");
                                });

                            b1.ComplexProperty<Dictionary<string, object>>("Departure", "FlightCatalog.Domain.Aggregates.Flight.Route#Route.Departure#AirportCode", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Value")
                                        .IsRequired()
                                        .HasMaxLength(3)
                                        .HasColumnType("character varying(3)")
                                        .HasColumnName("departure_airport");
                                });
                        });

                    b.ComplexProperty<Dictionary<string, object>>("Schedule", "FlightCatalog.Domain.Aggregates.Flight.Schedule#Schedule", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("Arrival")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("scheduled_arrival");

                            b1.Property<DateTimeOffset>("Departure")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("scheduled_departure");
                        });

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("flights", "flight_catalog");
                });
#pragma warning restore 612, 618
        }
    }
}
