global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: flights-platform
    environment: dev

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: "flights-platform-api"
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: ["host.docker.internal:50943"]
        labels:
          service: flights-api

  - job_name: "flights-platform-notification-worker"
    static_configs:
      - targets: ["notification-worker:9101"]
        labels:
          service: notification-worker

  - job_name: "flights-platform-analytics-worker"
    static_configs:
      - targets: ["analytics-worker:9102"]
        labels:
          service: analytics-worker