<#
.SYNOPSIS
    Deploys the SPA to Cloudflare Pages (CDN), patches API CORS, sets up CI.

.DESCRIPTION
    One-shot automation for the Phase 9 CDN demo. Safe to re-run.
    Stages:
      1. Verify prerequisites (node, npm).
      2. Resolve Cloudflare API token + account id (stored in .env.local).
      3. Build the SPA (npm ci + npm run build).
      4. Create the Cloudflare Pages project (idempotent).
      5. Deploy the SPA dist folder.
      6. Patch API Program.cs with a CORS policy for the CDN origin.
      7. Write a GitHub Actions workflow for auto-deploy on push to main.
      8. Print the resulting URL and next steps.

.PARAMETER ProjectName
    Cloudflare Pages project name. Default: practical-high-volume

.PARAMETER SpaPath
    Path to the frontend folder relative to repo root. Default: frontend

.PARAMETER ApiProjectPath
    Path to the API project. Default: src/Hosts/FlightsPlatform.Api

.PARAMETER SkipBuild
    Skip npm ci + npm run build (reuse existing dist).

.PARAMETER SkipCors
    Skip editing Program.cs.

.PARAMETER SkipCi
    Skip writing the GitHub Actions workflow.

.EXAMPLE
    .\scripts\cdn\Deploy-Cdn.ps1

.EXAMPLE
    .\scripts\cdn\Deploy-Cdn.ps1 -ProjectName my-flights -SkipCi
#>

[CmdletBinding()]
param(
    [string]$ProjectName     = "practical-high-volume",
    [string]$SpaPath         = "frontend",
    [string]$ApiProjectPath  = "src/Hosts/FlightsPlatform.Api",
    [switch]$SkipBuild,
    [switch]$SkipCors,
    [switch]$SkipCi
)

$ErrorActionPreference = "Stop"
$RepoRoot = (Get-Item $PSScriptRoot).Parent.Parent.FullName
Set-Location $RepoRoot

# ---------- helpers ----------
function Stage($n, $msg) { Write-Host "`n[$n] $msg" -ForegroundColor Cyan }
function Ok($msg)         { Write-Host "    [OK] $msg" -ForegroundColor Green }
function Warn($msg)       { Write-Host "    [!]  $msg" -ForegroundColor Yellow }
function Fail($msg)       { Write-Host "    [X]  $msg" -ForegroundColor Red; throw $msg }
function Info($msg)       { Write-Host "         $msg" -ForegroundColor DarkGray }

function Invoke-Native {
    param([string]$File, [string[]]$Args)
    & $File @Args
    if ($LASTEXITCODE -ne 0) { Fail "$File exited with code $LASTEXITCODE" }
}

# ---------- 1. Prereqs ----------
Stage 1 "Verifying prerequisites"

foreach ($cmd in "node","npm") {
    if (-not (Get-Command $cmd -ErrorAction SilentlyContinue)) {
        Fail "$cmd not found. Install Node.js from https://nodejs.org/"
    }
    Ok "$cmd $( & $cmd --version )"
}

if (-not (Test-Path $SpaPath)) { Fail "SPA folder '$SpaPath' not found." }
if (-not (Test-Path $ApiProjectPath)) { Warn "API path '$ApiProjectPath' not found; CORS step will be skipped."; $SkipCors = $true }

# ---------- 2. Cloudflare credentials ----------
Stage 2 "Resolving Cloudflare credentials"

$EnvFile = Join-Path $RepoRoot ".env.local"

# Load existing .env.local if present
if (Test-Path $EnvFile) {
    Get-Content $EnvFile | ForEach-Object {
        if ($_ -match '^\s*([^#=]+?)\s*=\s*(.+)\s*$') {
            Set-Item -Path "Env:$($matches[1])" -Value $matches[2] -ErrorAction SilentlyContinue
        }
    }
    Ok "Loaded .env.local"
}

if (-not $env:CLOUDFLARE_API_TOKEN) {
    Write-Host "    Cloudflare API token is required." -ForegroundColor Yellow
    Info "Create one at: https://dash.cloudflare.com/profile/api-tokens"
    Info "Template: 'Edit Cloudflare Workers' — it covers Pages too."
    $secure = Read-Host "    Paste token" -AsSecureString
    $env:CLOUDFLARE_API_TOKEN = [System.Runtime.InteropServices.Marshal]::PtrToStringAuto(
        [System.Runtime.InteropServices.Marshal]::SecureStringToBSTR($secure))
}

# Resolve account id via API
try {
    $resp = Invoke-RestMethod -Uri "https://api.cloudflare.com/client/v4/accounts" `
        -Headers @{ Authorization = "Bearer $env:CLOUDFLARE_API_TOKEN" }
    if (-not $resp.success -or $resp.result.Count -eq 0) {
        Fail "Cloudflare rejected the token or no accounts found."
    }
    $env:CLOUDFLARE_ACCOUNT_ID = $resp.result[0].id
    Ok "Account: $($resp.result[0].name)  ($($env:CLOUDFLARE_ACCOUNT_ID))"
} catch {
    Fail "Failed to query Cloudflare accounts: $($_.Exception.Message)"
}

# Persist to .env.local (git-ignored) and ensure it is ignored
$envLines = @(
    "# Auto-generated by scripts/cdn/Deploy-Cdn.ps1",
    "CLOUDFLARE_API_TOKEN=$env:CLOUDFLARE_API_TOKEN",
    "CLOUDFLARE_ACCOUNT_ID=$env:CLOUDFLARE_ACCOUNT_ID"
)
$envLines | Set-Content -Path $EnvFile -Encoding UTF8
Ok "Saved credentials to .env.local"

$gitignore = Join-Path $RepoRoot ".gitignore"
$gitignoreContent = if (Test-Path $gitignore) { Get-Content $gitignore -Raw } else { "" }
if ($gitignoreContent -notmatch '(?m)^\.env\.local\s*$') {
    Add-Content -Path $gitignore -Value "`n.env.local"
    Ok "Added .env.local to .gitignore"
}

# ---------- 3. Build SPA ----------
Stage 3 "Building SPA"

if ($SkipBuild) {
    Warn "SkipBuild set — reusing existing dist."
} else {
    Push-Location (Join-Path $RepoRoot $SpaPath)
    try {
        if (Test-Path "package-lock.json") {
            Invoke-Native "npm" @("ci")
        } else {
            Invoke-Native "npm" @("install")
        }
        Invoke-Native "npm" @("run","build")
    } finally { Pop-Location }
    Ok "Build finished"
}

# Locate the browser dist folder (Angular puts it under dist/<app>/browser)
$indexHtml = Get-ChildItem -Path (Join-Path $RepoRoot "$SpaPath/dist") -Recurse -Filter "index.html" `
    -ErrorAction SilentlyContinue | Where-Object { $_.Directory.Name -eq "browser" } | Select-Object -First 1
if (-not $indexHtml) {
    # Fallback: any index.html under dist
    $indexHtml = Get-ChildItem -Path (Join-Path $RepoRoot "$SpaPath/dist") -Recurse -Filter "index.html" `
        -ErrorAction SilentlyContinue | Select-Object -First 1
}
if (-not $indexHtml) { Fail "Could not find built index.html under $SpaPath/dist" }
$DistPath = $indexHtml.DirectoryName
Ok "Dist: $DistPath"

# ---------- 4. Create Pages project ----------
Stage 4 "Ensuring Cloudflare Pages project '$ProjectName'"

# `wrangler pages project create` fails if it exists; we tolerate that.
$createOutput = & npx --yes wrangler@latest pages project create $ProjectName `
    --production-branch=main 2>&1
if ($LASTEXITCODE -ne 0) {
    if ($createOutput -match "already exists" -or $createOutput -match "8000007") {
        Ok "Project already exists"
    } else {
        Fail "wrangler pages project create failed:`n$createOutput"
    }
} else {
    Ok "Project created"
}

# ---------- 5. Deploy ----------
Stage 5 "Deploying to Cloudflare Pages"

$deployOutput = & npx --yes wrangler@latest pages deploy $DistPath `
    --project-name=$ProjectName --branch=main --commit-dirty=true 2>&1
if ($LASTEXITCODE -ne 0) { Fail "wrangler pages deploy failed:`n$deployOutput" }

$deployUrl = ($deployOutput | Select-String -Pattern 'https://[a-z0-9\-\.]+\.pages\.dev' -AllMatches |
    ForEach-Object { $_.Matches } | ForEach-Object { $_.Value } | Select-Object -Last 1)

if (-not $deployUrl) {
    $deployUrl = "https://$ProjectName.pages.dev"
    Warn "Could not parse deployment URL; assuming $deployUrl"
}
Ok "Deployed: $deployUrl"

$CdnOrigin = "https://$ProjectName.pages.dev"

# ---------- 6. Patch API CORS ----------
if (-not $SkipCors) {
    Stage 6 "Patching API CORS"

    $programCs = Join-Path $RepoRoot "$ApiProjectPath/Program.cs"
    if (-not (Test-Path $programCs)) { Fail "Program.cs not found at $programCs" }

    $content = Get-Content $programCs -Raw
    $backup  = "$programCs.bak"
    Copy-Item $programCs $backup -Force
    Ok "Backup: $backup"

    # 6a. Ensure the CORS policy is registered
    if ($content -notmatch 'AddPolicy\(\s*"SpaCdn"') {
        $corsBlock = @"

// --- CDN CORS (added by scripts/cdn/Deploy-Cdn.ps1) ---
builder.Services.AddCors(options =>
{
    options.AddPolicy("SpaCdn", policy =>
    {
        policy.WithOrigins(
                "http://localhost:4200",
                "$CdnOrigin")
              .AllowAnyHeader()
              .AllowAnyMethod()
              .AllowCredentials();
    });
});
// --- end CDN CORS ---

"@

        # Anchor: after AddControllers / AddEndpointsApiExplorer / first builder.Services.*
        $anchor = [regex]::Match($content, '(?m)^builder\.Services\.[^\r\n]+\r?\n')
        if (-not $anchor.Success) { Fail "Could not find a builder.Services anchor in Program.cs" }
        $insertAt = $anchor.Index + $anchor.Length
        $content = $content.Insert($insertAt, $corsBlock)
        Ok "Inserted AddCors registration"
    } else {
        Warn "AddPolicy(\"SpaCdn\") already present — updating origin only"
        $content = $content -replace '"(https?://[^"]*\.pages\.dev)"', "`"$CdnOrigin`""
    }

    # 6b. Ensure app.UseCors is called
    if ($content -notmatch 'UseCors\(\s*"SpaCdn"') {
        $useCorsLine = 'app.UseCors("SpaCdn");' + [Environment]::NewLine
        $appAnchor = [regex]::Match($content, '(?m)^(app\.UseRouting\(\)|app\.MapControllers\(\))')
        if ($appAnchor.Success) {
            $content = $content.Insert($appAnchor.Index, $useCorsLine)
            Ok "Inserted app.UseCors(\"SpaCdn\")"
        } else {
            Warn "No UseRouting/MapControllers anchor; add 'app.UseCors(\"SpaCdn\");' manually before endpoints"
        }
    } else {
        Warn "app.UseCors(\"SpaCdn\") already present"
    }

    Set-Content -Path $programCs -Value $content -Encoding UTF8
    Ok "Program.cs updated"
} else {
    Stage 6 "Skipping CORS patch"
}

# ---------- 7. GitHub Actions workflow ----------
if (-not $SkipCi) {
    Stage 7 "Writing GitHub Actions workflow"

    $workflowDir = Join-Path $RepoRoot ".github/workflows"
    New-Item -ItemType Directory -Force -Path $workflowDir | Out-Null
    $workflowPath = Join-Path $workflowDir "deploy-spa-cdn.yml"

    $workflow = @"
name: Deploy SPA to Cloudflare Pages

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-spa-cdn.yml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: frontend/package-lock.json

      - name: Install
        working-directory: frontend
        run: npm ci

      - name: Build
        working-directory: frontend
        run: npm run build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: `${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: `${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy frontend/dist --project-name=$ProjectName --branch=main
"@

    Set-Content -Path $workflowPath -Value $workflow -Encoding UTF8
    Ok "Wrote $workflowPath"
    Warn "Add CLOUDFLARE_API_TOKEN and CLOUDFLARE_ACCOUNT_ID to GitHub repo secrets to enable CI."
} else {
    Stage 7 "Skipping CI workflow"
}

# ---------- 8. Summary ----------
Stage 8 "Done"

Write-Host ""
Write-Host "  SPA URL:  $CdnOrigin" -ForegroundColor Green
Write-Host "  API origin: (unchanged)" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  Next steps:" -ForegroundColor Cyan
Write-Host "    - Run locally:   cd frontend; `$env:API_TARGET='https://localhost:50943'; npm run dev"
Write-Host "    - Verify CORS:   curl -I -H 'Origin: $CdnOrigin' https://localhost:50943/api/health"
Write-Host "    - Set CI secrets: CLOUDFLARE_API_TOKEN, CLOUDFLARE_ACCOUNT_ID"
Write-Host ""
Write-Host "  Re-run anytime with the same command — it is idempotent." -ForegroundColor DarkGray
Write-Host ""